import pandas as pd
import pandas_ta as ta

def run_strategy_scan(df: pd.DataFrame, symbol: str) -> dict:
    """
    Technical indicators calculate karta hai aur alert trigger check karta hai.
    Default Logic: EMA 9 / EMA 21 Crossover + RSI (14) filter
    """
    if df.empty or len(df) < 30:
        return {"signal": False}

    # Technical Indicators calculation
    df["EMA9"] = ta.ema(df["Close"], length=9)
    df["EMA21"] = ta.ema(df["Close"], length=21)
    df["RSI"] = ta.rsi(df["Close"], length=14)

    latest = df.iloc[-1]
    prev = df.iloc[-2]

    current_price = latest["Close"]
    current_rsi = latest["RSI"]

    # Bullish Alert: EMA 9 crosses above EMA 21 AND RSI > 50
    bullish_cross = (prev["EMA9"] <= prev["EMA21"]) and (latest["EMA9"] > latest["EMA21"])
    if bullish_cross and current_rsi > 50:
        msg = (
            f"🚀 *BUY SIGNAL ALERT: {symbol}*\n\n"
            f"• *Price:* `{current_price:.2f}`\n"
            f"• *RSI (14):* `{current_rsi:.2f}`\n"
            f"• *Condition:* EMA 9 crossed above EMA 21\n"
            f"• *Timeframe:* 15m\n"
            f"⚡ _Generated by MarketPro AI Scanner_"
        )
        return {"signal": True, "type": "BUY", "message": msg}

    # Bearish Alert: EMA 9 crosses below EMA 21 AND RSI < 50
    bearish_cross = (prev["EMA9"] >= prev["EMA21"]) and (latest["EMA9"] < latest["EMA21"])
    if bearish_cross and current_rsi < 50:
        msg = (
            f"🔻 *SELL SIGNAL ALERT: {symbol}*\n\n"
            f"• *Price:* `{current_price:.2f}`\n"
            f"• *RSI (14):* `{current_rsi:.2f}`\n"
            f"• *Condition:* EMA 9 crossed below EMA 21\n"
            f"• *Timeframe:* 15m\n"
            f"⚡ _Generated by MarketPro AI Scanner_"
        )
        return {"signal": True, "type": "SELL", "message": msg}

    return {"signal": False}
